# Generated by Django 5.2 on 2025-04-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultationslot",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "대기중"),
                    ("CONFIRMED", "확정"),
                    ("COMPLETED", "완료"),
                    ("CANCELLED", "취소"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
